spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/supply_db
spring.datasource.username=enterprise_admin
spring.datasource.password=secure_dev_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
