spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/supply_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:enterprise_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secure_dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=nexus-supply-chain-group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


# Logging Configurations
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT configuration keys
jwt.secret=9a67a86968d9fe15e8d197607a3c306716766d3a95d1222877a165b4c10757a3
jwt.expiration=3600000

# Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL_ENABLED:false}
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s
spring.cache.type=redis
