spring.application.name=demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/supply_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:enterprise_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secure_dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging Configurations
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JWT configuration keys
jwt.secret=9a67a86968d9fe15e8d197607a3c306716766d3a95d1222877a165b4c10757a3
jwt.expiration=3600000

# Redis Configuration
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD:}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL_ENABLED:false}
spring.cache.type=redis
